language: go
services:
  - mysql

env:
  - MYSQL_TEST="true"

go:
  - 1.7.5
  - 1.8rc3

matrix:
  allow_failures:
    - go: 1.8rc2

# cache:
#   directories:
#     - $GOPATH/src
#     - $GOPATH/pkg

# before_cache:
# - rm -rf $GOPATH/src/github.com/nsheridan/cashier/*
# - rm -rf $GOPATH/pkg/**/github.com/nsheridan/cashier

install:
  - go version

before_script:
  - mysql < db/seed.sql

sudo: false
script:
  - ./run_tests.sh
