language: go
services:
  - mysql

env:
  - MYSQL_TEST="true"

go:
  - 1.7.5
  - 1.8
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - go get -v github.com/golang/lint/golint

install:
  - go version

before_script:
  - mysql < db/seed.sql

sudo: false
script:
  - ./run_tests.sh
  - mysql -u root -B -e 'truncate issued_certs' certs
  - bash -c 'set -e; >coverage.txt; for d in $(go list ./... |egrep -v "vendor/|proto$"); do go test -covermode=count -coverprofile=p.out $d; if [ -f p.out ]; then cat p.out >> coverage.txt; rm p.out; fi; done'

after_success:
  - bash <(curl -s https://codecov.io/bash)
