language: go
services:
  - mysql

env:
  - MYSQL_TEST="true"

go:
  - 1.7.5
  - 1.8rc3

matrix:
  allow_failures:
    - go: 1.8rc2

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpam0g-dev
  - go get -v github.com/golang/lint/golint

install:
  - go version

before_script:
  - mysql < db/seed.sql

sudo: required
script:
  - ./run_tests.sh
