language: go
services:
  - mysql

env:
  - GO15VENDOREXPERIMENT=1 MYSQL_TEST_CONFIG="mysql:user:passwd:localhost"

go:
  - 1.5.4
  - 1.6.2
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - go get -v github.com/golang/lint/golint

before_script:
  - go run ./cmd/dbinit/dbinit.go -db_user user -db_password passwd

sudo: false
script:
  - go build -v ./...
  - go list ./... |grep -v vendor/ |xargs go test
  - gofmt -d $(find -type f -name '*.go' -not -path './vendor/*')
  - go list ./... |grep -v vendor/ |xargs go vet
  - go list ./... |grep -v vendor/ |xargs -L1 golint -set_exit_status
